export type Lang = "pt" | "en";

const pt = {
  navAria: "Principal",
  nav0: "Como funciona",
  nav1: "Explorar",
  nav2: "Evidência",
  nav3: "Resultado",
  nav5: "Por que existe",
  nav4: "Começar",
  eyebrow: "Modelo de ameaças para contratos Soroban",
  h1a: "Cole um contrato.",
  h1b: "Receba o modelo de ameaças.",
  heroSub:
    "Para equipes e revisores de contratos Soroban. O soroguard lê o WASM publicado na Stellar, sem código-fonte, e escreve um modelo de ameaças STRIDE e um plano de monitoramento on-chain. Cada afirmação diz de onde veio.",
  heroLink: "Explorar um contrato real",
  copy: "Copiar",
  copied: "Copiado",
  copyAria: "Copiar o comando npx soroguard artifact",
  copiedAria: "Comando copiado",
  dgAria:
    "Do endereço do contrato ao WASM, do WASM aos botões que cada função pode apertar, e daí para dois documentos. Linha contínua: fato do bytecode. Tracejada: observado na rede. Pontilhada: inferência.",
  dgS1: "O endereço",
  dgS2: "O binário na rede",
  dgS3: "Que botões cada função pode apertar",
  dgS4: "Dois documentos",
  dgWasmSub: "compilado, sem código-fonte",
  dgNet: "Rede Stellar, ao vivo",
  dgNetSub: "getEvents: o que o contrato emitiu de verdade",
  dgFns: "funções públicas",
  dgHosts: "host functions, os “botões”",
  dgNone: "não aperta nenhum",
  dgDoc1: "Ameaças",
  dgDoc2: "Monitoramento",
  dgRow1b: "sem require_auth",
  dgRow1c: "front-running no init",
  dgRow2b: "0 eventos em ~186 h",
  dgSameId: "mesmo ID",
  lgA: "A · fato do bytecode",
  lgB: "B · observado na rede",
  lgC: "C · inferência",
  lgP: "caminho possível",
  lgX: "não alcança: prova",
  hEyebrow: "Como funciona",
  hTitle: "Do endereço aos dois documentos, em quatro passos.",
  hSub: "Os mesmos passos do diagrama acima. Um comando faz tudo; você não precisa do repositório do contrato.",
  pAward: "Prêmio de um projeto Build",
  pRest: "restante do prêmio",
  pTranche: "tranche #2 · 30%",
  pUnlock: "Para liberar a tranche #2",
  pDoc1: "Modelo de ameaças STRIDE",
  pDoc2: "Plano de monitoramento on-chain",
  pFoot: "~35 times por rodada · templates publicados, sem ferramenta",
  xEyebrow: "Explorar",
  xTitle: "Clique numa função. Veja o que ela alcança.",
  xSub: "Dados reais de um escrow na mainnet. Para agir na rede, uma função precisa chamar host functions; aqui estão as quatro que importam, os “botões”.",
  xFnsAria: "Funções do contrato",
  xLegOk: "sem achado",
  xLegBad: "achado",
  xLegNone: "sem efeito",
  xRule:
    "Uma regra guia tudo: “não alcança X” é prova (tier A). “Alcança X” é sobre-aproximação, um caminho possível que o código pode nunca executar.",
  eEyebrow: "Evidência",
  eTitle: "Toda frase diz o quanto dá para confiar nela.",
  eSub: "Os mesmos traços do diagrama. Clique num nível para ver um exemplo real e o motivo.",
  eTiersAria: "Níveis de evidência",
  eExample: "exemplo real",
  eWhy: "Por que esse nível",
  oEyebrow: "A saída",
  oTitle: "Clique numa ameaça. Veja o alerta que a vigia.",
  oSub: "São dois arquivos. O modelo de ameaças lista o que pode dar errado; o plano de monitoramento diz o que vigiar em produção. Cada alerta nasce de uma ameaça e leva o ID dela.",
  oTmCount: "1 ameaça · 5 lacunas",
  oMpCount: "1 monitor",
  oTmAria: "Ameaças",
  oMpAria: "Monitores",
  oWhat: "O que é",
  oWatch: "O que o alerta vigia",
  oTodo: "Falta a equipe:",
  oSameId: "mesmo ID",
  oNoMon: "sem monitor",
  oNoThreat: "sem ameaça",
  oVerdTm: "Modelo de ameaças: precisa da equipe · 6 itens",
  oVerdMp: "Plano de monitoramento: precisa da equipe · 1 item",
  oRule:
    "A regra: monitor sem ameaça por trás é recusado. Por isso o plano nunca tem alerta solto, e o modelo nunca tem ameaça inventada para preencher uma letra.",
  oNumbers:
    "O corpus tem 75 contratos da mainnet. As 30 afirmações “não alcança require_auth” conferidas contra o código-fonte bateram, 30 de 30. O recall não foi medido: sem ground truth rotulado, ainda não sabemos o que a ferramenta deixa passar.",
  wEyebrow: "Por que existe",
  wTitle: "Feito para ajudar outros projetos na submissão.",
  wBody1:
    "Desde a rodada #44, todo projeto Build do Stellar Community Fund precisa entregar um modelo de ameaças STRIDE e um plano de monitoramento on-chain para liberar a tranche #2. São cerca de 35 times por rodada.",
  wBody2:
    "Os templates oficiais foram publicados, mas nenhuma ferramenta para preenchê-los. O soroguard faz a parte que o binário sustenta e deixa claro o que falta a equipe escrever.",
  sEyebrow: "Começar",
  sTitle: "Rode no seu contrato.",
  sTabsAria: "Formas de instalar",
  sFrom: "Do código-fonte",
  fBuilt: "feito com agentes de IA (declarado)",
  verbReach: "alcança",
  verbNone: "não alcança nada",
  of4: "de 4",
  stReach: "alcançável",
  stNot: "não alcança",
  stMiss: "faltando",
  hAuth: "exige assinatura",
  hWrite: "grava estado",
  hEvent: "emite evento",
  hCall: "chama outro contrato",
  gap: "Lacuna",
  possible: "possível",
};

export type Strings = typeof pt;

const en: Strings = {
  navAria: "Main",
  nav0: "How it works",
  nav1: "Explore",
  nav2: "Evidence",
  nav3: "Output",
  nav5: "Why it exists",
  nav4: "Get started",
  eyebrow: "Threat models for Soroban contracts",
  h1a: "Paste a contract.",
  h1b: "Get the threat model.",
  heroSub:
    "For teams and reviewers of Soroban contracts. soroguard reads the deployed WASM on Stellar, no source code needed, and writes a STRIDE threat model and an on-chain monitoring plan. Every claim says where it came from.",
  heroLink: "Explore a real contract",
  copy: "Copy",
  copied: "Copied",
  copyAria: "Copy the npx soroguard artifact command",
  copiedAria: "Command copied",
  dgAria:
    "From the contract address to the WASM, from the WASM to the buttons each function can press, and on to two documents. Solid line: bytecode fact. Dashed: observed on-chain. Dotted: inference.",
  dgS1: "The address",
  dgS2: "The binary on-chain",
  dgS3: "Which buttons each function can press",
  dgS4: "Two documents",
  dgWasmSub: "compiled, no source code",
  dgNet: "Stellar network, live",
  dgNetSub: "getEvents: what the contract actually emitted",
  dgFns: "public functions",
  dgHosts: "host functions, the “buttons”",
  dgNone: "presses none",
  dgDoc1: "Threats",
  dgDoc2: "Monitoring",
  dgRow1b: "no require_auth",
  dgRow1c: "init front-running",
  dgRow2b: "0 events in ~186 h",
  dgSameId: "same ID",
  lgA: "A · bytecode fact",
  lgB: "B · observed on-chain",
  lgC: "C · inference",
  lgP: "possible path",
  lgX: "does not reach: proof",
  hEyebrow: "How it works",
  hTitle: "From an address to two documents, in four steps.",
  hSub: "The same steps as the diagram above. One command does all of it; you do not need the contract's repository.",
  pAward: "A Build project's award",
  pRest: "rest of the award",
  pTranche: "tranche #2 · 30%",
  pUnlock: "To unlock tranche #2",
  pDoc1: "STRIDE threat model",
  pDoc2: "On-chain monitoring plan",
  pFoot: "~35 teams per round · templates published, no tooling",
  xEyebrow: "Explore",
  xTitle: "Click a function. See what it can reach.",
  xSub: "Real data from an escrow on mainnet. To act on the network a function has to call host functions; these are the four that matter, the “buttons”.",
  xFnsAria: "Contract functions",
  xLegOk: "no finding",
  xLegBad: "finding",
  xLegNone: "no effect",
  xRule:
    "One rule drives everything: “does not reach X” is proof (tier A). “Reaches X” is an over-approximation, a possible path the code may never take.",
  eEyebrow: "Evidence",
  eTitle: "Every sentence says how far to trust it.",
  eSub: "The same strokes as the diagram. Click a tier to see a real example and the reason behind it.",
  eTiersAria: "Evidence tiers",
  eExample: "real example",
  eWhy: "Why this tier",
  oEyebrow: "The output",
  oTitle: "Click a threat. See the alert that watches it.",
  oSub: "Two files. The threat model lists what can go wrong; the monitoring plan says what to watch in production. Every alert comes from a threat and carries its ID.",
  oTmCount: "1 threat · 5 gaps",
  oMpCount: "1 monitor",
  oTmAria: "Threats",
  oMpAria: "Monitors",
  oWhat: "What it is",
  oWatch: "What the alert watches",
  oTodo: "Left for the team:",
  oSameId: "same ID",
  oNoMon: "no monitor",
  oNoThreat: "no threat",
  oVerdTm: "Threat model: needs input · 6 items for the team",
  oVerdMp: "Monitoring plan: needs input · 1 item for the team",
  oRule:
    "The rule: a monitor with no threat behind it is rejected. So the plan never has a loose alert, and the model never has a threat invented to fill a letter.",
  oNumbers:
    "The corpus holds 75 mainnet contracts. All 30 “does not reach require_auth” claims checked against source held up, 30 of 30. Recall is not measured: with no labelled ground truth, we do not yet know what the tool misses.",
  wEyebrow: "Why it exists",
  wTitle: "Built to help other projects with their submission.",
  wBody1:
    "Since round #44, every Stellar Community Fund Build project has to hand in a STRIDE threat model and an on-chain monitoring plan to unlock tranche #2. That is roughly 35 teams per round.",
  wBody2:
    "The official templates were published, but no tooling to fill them. soroguard does the part the binary can support and makes clear what the team still has to write.",
  sEyebrow: "Get started",
  sTitle: "Run it on your contract.",
  sTabsAria: "Ways to install",
  sFrom: "From source",
  fBuilt: "built with AI coding agents (disclosed)",
  verbReach: "reaches",
  verbNone: "reaches nothing",
  of4: "of 4",
  stReach: "reachable",
  stNot: "not reached",
  stMiss: "missing",
  hAuth: "requires a signature",
  hWrite: "writes state",
  hEvent: "emits an event",
  hCall: "calls another contract",
  gap: "Gap",
  possible: "possible",
};

export const STRINGS: Record<Lang, Strings> = { pt, en };
